/*
 * Lablink
 * Lablink Swagger documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: laborit@blutspende.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.blutspende.lablink.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import org.blutspende.lablink.model.Gender;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BloodDonor
 */
public class BloodDonorTest {
    private final BloodDonor model = new BloodDonor();

    /**
     * Model tests for BloodDonor
     */
    @Test
    public void testBloodDonor() {
        // TODO: test BloodDonor
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    public void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'donationCode'
     */
    @Test
    public void donationCodeTest() {
        // TODO: test donationCode
    }

    /**
     * Test the property 'donorCode'
     */
    @Test
    public void donorCodeTest() {
        // TODO: test donorCode
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

}
