/*
 * Lablink
 * Lablink Swagger documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: laborit@blutspende.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.blutspende.lablink.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BoneMarrowDonor
 */
public class BoneMarrowDonorTest {
    private final BoneMarrowDonor model = new BoneMarrowDonor();

    /**
     * Model tests for BoneMarrowDonor
     */
    @Test
    public void testBoneMarrowDonor() {
        // TODO: test BoneMarrowDonor
    }

    /**
     * Test the property 'donorCode'
     */
    @Test
    public void donorCodeTest() {
        // TODO: test donorCode
    }

}
