/*
 * Lablink
 * Lablink Swagger documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: laborit@blutspende.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.blutspende.lablink.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.blutspende.lablink.model.BloodDonor;
import org.blutspende.lablink.model.BoneMarrowDonor;
import org.blutspende.lablink.model.OrderExamination;
import org.blutspende.lablink.model.OrderStateType;
import org.blutspende.lablink.model.OrderType;
import org.blutspende.lablink.model.Patient;
import org.blutspende.lablink.model.Pseudonym;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Order
 */
public class OrderTest {
    private final Order model = new Order();

    /**
     * Model tests for Order
     */
    @Test
    public void testOrder() {
        // TODO: test Order
    }

    /**
     * Test the property 'bloodDonor'
     */
    @Test
    public void bloodDonorTest() {
        // TODO: test bloodDonor
    }

    /**
     * Test the property 'boneMarrowDonor'
     */
    @Test
    public void boneMarrowDonorTest() {
        // TODO: test boneMarrowDonor
    }

    /**
     * Test the property 'examinations'
     */
    @Test
    public void examinationsTest() {
        // TODO: test examinations
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    public void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'orderCreationDateTime'
     */
    @Test
    public void orderCreationDateTimeTest() {
        // TODO: test orderCreationDateTime
    }

    /**
     * Test the property 'patient'
     */
    @Test
    public void patientTest() {
        // TODO: test patient
    }

    /**
     * Test the property 'pseudonym'
     */
    @Test
    public void pseudonymTest() {
        // TODO: test pseudonym
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
