/*
 * Lablink
 * Lablink Swagger documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: laborit@blutspende.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.blutspende.lablink.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.blutspende.lablink.model.OrderResultStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderResult
 */
public class OrderResultTest {
    private final OrderResult model = new OrderResult();

    /**
     * Model tests for OrderResult
     */
    @Test
    public void testOrderResult() {
        // TODO: test OrderResult
    }

    /**
     * Test the property 'analyte'
     */
    @Test
    public void analyteTest() {
        // TODO: test analyte
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'resultType'
     */
    @Test
    public void resultTypeTest() {
        // TODO: test resultType
    }

    /**
     * Test the property 'resultYieldDateTime'
     */
    @Test
    public void resultYieldDateTimeTest() {
        // TODO: test resultYieldDateTime
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'unit'
     */
    @Test
    public void unitTest() {
        // TODO: test unit
    }

}
