/*
 * Lablink
 * Lablink Swagger documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: laborit@blutspende.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.blutspende.lablink.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.blutspende.lablink.model.OrderResult;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderExamination
 */
public class OrderExaminationTest {
    private final OrderExamination model = new OrderExamination();

    /**
     * Model tests for OrderExamination
     */
    @Test
    public void testOrderExamination() {
        // TODO: test OrderExamination
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'results'
     */
    @Test
    public void resultsTest() {
        // TODO: test results
    }

    /**
     * Test the property 'sampleCodes'
     */
    @Test
    public void sampleCodesTest() {
        // TODO: test sampleCodes
    }

    /**
     * Test the property 'sampleDate'
     */
    @Test
    public void sampleDateTest() {
        // TODO: test sampleDate
    }

    /**
     * Test the property 'sampleTime'
     */
    @Test
    public void sampleTimeTest() {
        // TODO: test sampleTime
    }

}
