/*
 * Lablink
 * Lablink Swagger documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: laborit@blutspende.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import org.openapitools.client.model.Gender;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BloodDonor
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-12T04:43:46.153841900+01:00[Europe/Berlin]")
public class BloodDonor {
  public static final String SERIALIZED_NAME_DATE_OF_BIRTH = "dateOfBirth";
  @SerializedName(SERIALIZED_NAME_DATE_OF_BIRTH)
  private LocalDate dateOfBirth;

  public static final String SERIALIZED_NAME_DONATION_CODE = "donationCode";
  @SerializedName(SERIALIZED_NAME_DONATION_CODE)
  private String donationCode;

  public static final String SERIALIZED_NAME_DONOR_CODE = "donorCode";
  @SerializedName(SERIALIZED_NAME_DONOR_CODE)
  private String donorCode;

  public static final String SERIALIZED_NAME_GENDER = "gender";
  @SerializedName(SERIALIZED_NAME_GENDER)
  private Gender gender;

  public BloodDonor() {
  }

  public BloodDonor dateOfBirth(LocalDate dateOfBirth) {
    
    this.dateOfBirth = dateOfBirth;
    return this;
  }

   /**
   * The date of birth (yyyy-MM-dd)
   * @return dateOfBirth
  **/
  @javax.annotation.Nonnull
  public LocalDate getDateOfBirth() {
    return dateOfBirth;
  }


  public void setDateOfBirth(LocalDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }


  public BloodDonor donationCode(String donationCode) {
    
    this.donationCode = donationCode;
    return this;
  }

   /**
   * The donation code
   * @return donationCode
  **/
  @javax.annotation.Nonnull
  public String getDonationCode() {
    return donationCode;
  }


  public void setDonationCode(String donationCode) {
    this.donationCode = donationCode;
  }


  public BloodDonor donorCode(String donorCode) {
    
    this.donorCode = donorCode;
    return this;
  }

   /**
   * The donor code
   * @return donorCode
  **/
  @javax.annotation.Nonnull
  public String getDonorCode() {
    return donorCode;
  }


  public void setDonorCode(String donorCode) {
    this.donorCode = donorCode;
  }


  public BloodDonor gender(Gender gender) {
    
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @javax.annotation.Nonnull
  public Gender getGender() {
    return gender;
  }


  public void setGender(Gender gender) {
    this.gender = gender;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BloodDonor bloodDonor = (BloodDonor) o;
    return Objects.equals(this.dateOfBirth, bloodDonor.dateOfBirth) &&
        Objects.equals(this.donationCode, bloodDonor.donationCode) &&
        Objects.equals(this.donorCode, bloodDonor.donorCode) &&
        Objects.equals(this.gender, bloodDonor.gender);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateOfBirth, donationCode, donorCode, gender);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BloodDonor {\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    donationCode: ").append(toIndentedString(donationCode)).append("\n");
    sb.append("    donorCode: ").append(toIndentedString(donorCode)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("dateOfBirth");
    openapiFields.add("donationCode");
    openapiFields.add("donorCode");
    openapiFields.add("gender");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("dateOfBirth");
    openapiRequiredFields.add("donationCode");
    openapiRequiredFields.add("donorCode");
    openapiRequiredFields.add("gender");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to BloodDonor
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BloodDonor.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BloodDonor is not found in the empty JSON string", BloodDonor.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BloodDonor.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BloodDonor` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BloodDonor.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("donationCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `donationCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("donationCode").toString()));
      }
      if (!jsonObj.get("donorCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `donorCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("donorCode").toString()));
      }
      // validate the required field `gender`
      Gender.validateJsonElement(jsonObj.get("gender"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BloodDonor.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BloodDonor' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BloodDonor> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BloodDonor.class));

       return (TypeAdapter<T>) new TypeAdapter<BloodDonor>() {
           @Override
           public void write(JsonWriter out, BloodDonor value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BloodDonor read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BloodDonor given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BloodDonor
  * @throws IOException if the JSON string is invalid with respect to BloodDonor
  */
  public static BloodDonor fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BloodDonor.class);
  }

 /**
  * Convert an instance of BloodDonor to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

