/*
 * Lablink
 * Lablink Swagger documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: laborit@blutspende.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets OrderStateType
 */
@JsonAdapter(OrderStateType.Adapter.class)
public enum OrderStateType {
  
  ConfirmatoryState("CONFIRMATORY"),
  
  DeletedState("DELETED"),
  
  EnteredState("ENTERED"),
  
  FinalizedState("FINALIZED"),
  
  ProcessingState("PROCESSING"),
  
  WaitingForMaterialState("WAITING_FOR_MATERIAL");

  private String value;

  OrderStateType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OrderStateType fromValue(String value) {
    for (OrderStateType b : OrderStateType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<OrderStateType> {
    @Override
    public void write(final JsonWriter jsonWriter, final OrderStateType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OrderStateType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OrderStateType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    OrderStateType.fromValue(value);
  }
}

