/*
 * Lablink
 * Lablink Swagger documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: laborit@blutspende.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ApiError;
import org.openapitools.client.model.LoginResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthApi
 */
@Disabled
public class AuthApiTest {

    private final AuthApi api = new AuthApi();

    /**
     * Login
     *
     * Login and request access token.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void loginV3Test() throws ApiException {
        String grantType = null;
        String password = null;
        String scope = null;
        String username = null;
        String xApiVersion = null;
        LoginResponse response = api.loginV3(grantType, password, scope, username, xApiVersion);
        // TODO: test validations
    }

}
