/*
 * Lablink
 * Lablink Swagger documentation
 *
 * The version of the OpenAPI document: 3.0
 * Contact: laborit@blutspende.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ApiError;
import org.openapitools.client.model.GetOrderStatesV3200Response;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrderStateApi
 */
@Disabled
public class OrderStateApiTest {

    private final OrderStateApi api = new OrderStateApi();

    /**
     * Get order states
     *
     * Gets the state of all orders.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getOrderStatesV3Test() throws ApiException {
        Integer page = null;
        Integer pageSize = null;
        String xApiVersion = null;
        List<String> sort = null;
        String createdFrom = null;
        String createdTo = null;
        String searchContent = null;
        String state = null;
        String type = null;
        GetOrderStatesV3200Response response = api.getOrderStatesV3(page, pageSize, xApiVersion, sort, createdFrom, createdTo, searchContent, state, type);
        // TODO: test validations
    }

    /**
     * Get selected order states
     *
     * Gets order states based on the specified selection.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSelectionOrdersStatesV3Test() throws ApiException {
        UUID id = null;
        Integer page = null;
        Integer pageSize = null;
        String xApiVersion = null;
        List<String> sort = null;
        GetOrderStatesV3200Response response = api.getSelectionOrdersStatesV3(id, page, pageSize, xApiVersion, sort);
        // TODO: test validations
    }

}
